obj-$(CONFIG_INFINIBAND_RXE) += ib_rxe.o ib_rxe_net.o ib_rxe_sample.o

ib_rxe-y := \
	rxe.o \
	rxe_comp.o \
	rxe_req.o \
	rxe_resp.o \
	rxe_recv.o \
	rxe_pool.o \
	rxe_queue.o \
	rxe_verbs.o \
	rxe_av.o \
	rxe_srq.o \
	rxe_qp.o \
	rxe_cq.o \
	rxe_mr.o \
	rxe_dma.o \
	rxe_opcode.o \
	rxe_mmap.o \
	rxe_arbiter.o \
	rxe_icrc.o \
	rxe_mcast.o \
	rxe_task.o

ib_rxe_net-y := \
	rxe_net.o \
	rxe_net_sysfs.o

ib_rxe_sample-y := \
	rxe_sample.o
